#!/bin/bash
curl -o ari.gif http://nationalchamps.net/Helmet_Project/NFL_Cardinals.gif
curl -o atl.gif http://nationalchamps.net/Helmet_Project/NFL_Falcons.gif
curl -o bal.gif http://nationalchamps.net/Helmet_Project/NFL_Ravens.gif
curl -o buf.gif http://nationalchamps.net/Helmet_Project/NFL_Bills.gif
curl -o car.gif http://nationalchamps.net/Helmet_Project/NFL_Panthers.gif
curl -o chi.gif http://nationalchamps.net/Helmet_Project/NFL_Bears1.gif
curl -o cin.gif http://nationalchamps.net/Helmet_Project/NFL_Bengals.gif
curl -o cle.gif http://nationalchamps.net/Helmet_Project/NFL_Browns.gif
curl -o dal.gif http://nationalchamps.net/Helmet_Project/NFL_Cowboys.gif
curl -o den.gif http://nationalchamps.net/Helmet_Project/NFL_Broncos.gif
curl -o det.gif http://nationalchamps.net/Helmet_Project/NFL_Lions.gif
curl -o gb.gif http://nationalchamps.net/Helmet_Project/NFL_Packers.gif
curl -o hou.gif http://nationalchamps.net/Helmet_Project/NFL_Texans.gif
curl -o ind.gif http://nationalchamps.net/Helmet_Project/NFL_Colts.gif
curl -o jax.gif http://nationalchamps.net/Helmet_Project/NFL_Jaguars.gif
curl -o kc.gif http://nationalchamps.net/Helmet_Project/NFL_Chiefs.gif
curl -o lac.gif http://nationalchamps.net/Helmet_Project/NFL_Chargers.gif
curl -o lar.gif http://nationalchamps.net/Helmet_Project/NFL_Rams.gif
curl -o mia.gif http://nationalchamps.net/Helmet_Project/NFL_Dolphins.gif
curl -o min.gif http://nationalchamps.net/Helmet_Project/NFL_Vikings.gif
curl -o ne.gif http://nationalchamps.net/Helmet_Project/NFL_Patriots.gif
curl -o no.gif http://nationalchamps.net/Helmet_Project/NFL_Saints.gif
curl -o nyg.gif http://nationalchamps.net/Helmet_Project/NFL_Giants.gif
curl -o nyj.gif http://nationalchamps.net/Helmet_Project/NFL_Jets.gif
curl -o oak.gif http://nationalchamps.net/Helmet_Project/NFL_Raiders1.gif
curl -o phi.gif http://nationalchamps.net/Helmet_Project/NFL_Eagles.gif
curl -o pit.gif http://nationalchamps.net/Helmet_Project/NFL_Steelers.gif
curl -o sf.gif http://nationalchamps.net/Helmet_Project/NFL_49ers.gif
curl -o sea.gif http://nationalchamps.net/Helmet_Project/NFL_Seahawks.gif
curl -o tb.gif http://nationalchamps.net/Helmet_Project/NFL_Buccaneers.gif
curl -o ten.gif http://nationalchamps.net/Helmet_Project/NFL_Titans.gif
curl -o wsh.gif http://nationalchamps.net/Helmet_Project/NFL_Redskins.gif
