# Generated by Django 2.0.7 on 2018-07-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0003_auto_20180721_1429'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='preference',
            name='favorite_team',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='league',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='status',
        ),
    ]
