# Generated by Django 2.0.7 on 2018-08-02 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("picker", "0003_auto_20180801_0800"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ("start_time", "away")},
        ),
        migrations.RenameField(
            model_name="game",
            old_name="kickoff",
            new_name="start_time",
        ),
        migrations.RemoveField(
            model_name="team",
            name="image",
        ),
        migrations.AddField(
            model_name="league",
            name="avg_game_duration",
            field=models.PositiveIntegerField(default=240),
        ),
        migrations.AlterField(
            model_name="team",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="picker.Conference",
            ),
        ),
    ]
