# Generated by Django 2.0.7 on 2018-07-30 23:36

from django.db import migrations, models
import picker.models


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0004_auto_20180729_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='current_season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(default=picker.models.temp_slug),
        ),
    ]
