# Generated by Django 2.1 on 2018-08-28 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("picker", "0006_auto_20180824_1356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamepick",
            name="pick",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamepicks",
                to="picker.PickSet",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picker_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
