# Generated by Django 2.0.7 on 2018-07-30 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0006_remove_pickermembership_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickergrouping',
            name='members',
        ),
        migrations.AddField(
            model_name='pickermembership',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='picker.PickerGrouping'),
            preserve_default=False,
        ),
    ]
