# Generated by Django 2.2.9 on 2019-12-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picker", "0011_team_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSetPicks",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("picker.gameset",),
        ),
        migrations.RemoveField(
            model_name="league",
            name="is_pickable",
        ),
        migrations.AddField(
            model_name="game",
            name="away_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="home_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamepick",
            name="confidence",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gameset",
            name="label",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
