# Generated by Django 5.1.3 on 2024-12-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picker", "0013_alter_tv_len"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
